allow script to continue if urpme fails
This allows the script to continue if urpme files.  This can happen
when devstack attempts to remove a package that is already present.

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -980,7 +980,7 @@ function uninstall_package() {
     elif is_suse; then
         sudo zypper rm "$@"
     elif is_mageia; then
-        sudo urpme "$@"
+        sudo urpme "$@" || echo "urpme failed"
     else
         exit_distro_not_supported "uninstalling packages"
     fi
